import image from "../assets/Images/Img1.jpg"

export const OrderListDataRecords = [
    {
        id: 1,
        img: image,
        Title: "Chicken Breast Fillet ,Boneless Matu MaMarineted 6 Ounce Raw,Invaid",
        Brand: "Hormel Black Labelmany",
        Price: "$40.67/6+1LB",
        Quantity: "0 x 6+ 1LB",
        Total: "$0",
    },
    {
        id: 2,
        img: image,
        Title: "Chicken Breast Fillet ,Boneless Matu MaMarineted 6 Ounce Raw,Invaid",
        Brand: "Hormel Black Labelmany",
        Price: "$40.67/6+1LB",
        Quantity: "0 x 6+ 1LB",
        Total: "$900000",
    },
    {
        id: 3,
        img: image,
        Title: "Chicken Breast Fillet ,Boneless Matu MaMarineted 6 Ounce Raw,Invaid",
        Brand: "Hormel Black Labelmany",
        Price: "$40.67/6+1LB",
        Quantity: "0 x 6+ 1LB",
        Total: "$3550",
    },
    {
        id: 4,
        img: image,
        Title: "Chicken Breast Fillet ,Boneless Matu MaMarineted 6 Ounce Raw,Invaid",
        Brand: "Hormel Black Labelmany",
        Price: "$40.67/6+1LB",
        Quantity: "0 x 6+ 1LB",
        Total: "$2340",
    },
    {
        id: 5,
        img: image,
        Title: "Chicken Breast Fillet ,Boneless Matu MaMarineted 6 Ounce Raw,Invaid",
        Brand: "Hormel Black Labelmany",
        Price: "$40.67/6+1LB",
        Quantity: "0 x 6+ 1LB",
        Total: "$43530",
    },
    {
        id: 6,
        img: image,
        Title: "Chicken Breast Fillet ,Boneless Matu MaMarineted 6 Ounce Raw,Invaid",
        Brand: "Hormel Black Labelmany",
        Price: "$40.67/6+1LB",
        Quantity: "0 x 6+ 1LB",
        Total: "$234320",
    },
    {
        id: 7,
        img: image,
        Title: "Chicken Breast Fillet ,Boneless Matu MaMarineted 6 Ounce Raw,Invaid",
        Brand: "Hormel Black Labelmany",
        Price: "$40.67/6+1LB",
        Quantity: "0 x 6+ 1LB",
        Total: "0",
    },
    {
        id: 8,
        img: image,
        Title: "Chicken Breast Fillet ,Boneless Matu MaMarineted 6 Ounce Raw,Invaid",
        Brand: "Hormel Black Labelmany",
        Price: "$40.67/6+1LB",
        Quantity: "0 x 6+ 1LB",
        Total: "0",
    },
    {
        id: 9,
        img: image,
        Title: "Chicken Breast Fillet ,Boneless Matu MaMarineted 6 Ounce Raw,Invaid",
        Brand: "Hormel Black Labelmany",
        Price: "$40.67/6+1LB",
        Quantity: "0 x 6+ 1LB",
        Total: "0",
    },
    {
        id: 10,
        img: image,
        Title: "Chicken Breast Fillet ,Boneless Matu MaMarineted 6 Ounce Raw,Invaid",
        Brand: "Hormel Black Labelmany",
        Price: "$40.67/6+1LB",
        Quantity: "0 x 6+ 1LB",
        Total: "0",
    },
]